"""Human-approval-gated execution of RecommendationActions against Graph8.

No Graph8 write happens until a RecommendationAction has status=APPROVED, set by
an authenticated user via the API layer in the same call that triggers this.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.models.audit import AuditLog
from app.models.pattern import Pattern, PatternOccurrence, Recommendation, RecommendationAction
from app.services.graph8.base import Graph8Provider


def propose_action(session: Session, *, recommendation_id: uuid.UUID, action_type: str) -> RecommendationAction:
    action = RecommendationAction(
        recommendation_id=recommendation_id, action_type=action_type, status="proposed"
    )
    session.add(action)
    session.flush()
    return action


def approve_and_execute_action(
    session: Session,
    *,
    organization_id: uuid.UUID,
    action: RecommendationAction,
    approved_by_user_id: uuid.UUID,
    provider: Graph8Provider,
) -> RecommendationAction:
    recommendation = session.get(Recommendation, action.recommendation_id)
    pattern = session.get(Pattern, recommendation.pattern_id)

    action.status = "approved"
    action.approved_by_user_id = approved_by_user_id
    action.approved_at = datetime.now(timezone.utc)
    session.flush()

    sample_occurrence = (
        session.query(PatternOccurrence)
        .filter(PatternOccurrence.pattern_id == pattern.id, PatternOccurrence.outcome == "lost")
        .first()
    )

    try:
        if action.action_type == "create_task":
            graph8_id = provider.create_task(
                graph8_deal_id=sample_occurrence.deal_id.hex if sample_occurrence else "",
                title=recommendation.title,
                description=(
                    f"{recommendation.explanation}\n\nRecommended action: {recommendation.recommended_action}\n\n"
                    f"Department: {recommendation.department.value}. Generated by Graph8 Revenue Learning "
                    f"from pattern '{pattern.name}' ({pattern.lost_count} lost / {pattern.won_count} won deals)."
                ),
            )
            action.graph8_object_type = "task"
        else:
            graph8_id = provider.create_note(
                graph8_deal_id=sample_occurrence.deal_id.hex if sample_occurrence else "",
                body=f"Revenue Learning insight: {recommendation.title}. {recommendation.explanation}",
            )
            action.graph8_object_type = "note"
        action.graph8_object_id = graph8_id
        action.status = "created"
        recommendation.status = "actioned"
    except Exception as exc:  # noqa: BLE001
        action.status = "failed"
        action.error = str(exc)

    session.add(
        AuditLog(
            organization_id=organization_id,
            actor_user_id=approved_by_user_id,
            action="approve_recommendation_action",
            entity_type="recommendation_action",
            entity_id=str(action.id),
            log_metadata={
                "recommendation_id": str(recommendation.id),
                "graph8_object_type": action.graph8_object_type,
                "graph8_object_id": action.graph8_object_id,
                "status": action.status,
            },
        )
    )
    session.flush()
    return action
