/** Human-approval-gated execution of RecommendationActions against Graph8.
 * Ported from backend/app/services/recommendations/actions.py. */
import { prisma } from "../../db";
import type { Graph8Provider } from "../graph8/base";
import type { RecommendationAction } from "@prisma/client";

export async function proposeAction(args: {
  recommendationId: string;
  actionType: string;
}): Promise<RecommendationAction> {
  return prisma.recommendationAction.create({
    data: { recommendationId: args.recommendationId, actionType: args.actionType, status: "proposed" },
  });
}

export async function approveAndExecuteAction(args: {
  organizationId: string;
  action: RecommendationAction;
  approvedByUserId: string;
  provider: Graph8Provider;
}): Promise<RecommendationAction> {
  const { organizationId, approvedByUserId, provider } = args;
  let action = args.action;

  const recommendation = await prisma.recommendation.findUniqueOrThrow({ where: { id: action.recommendationId } });
  const pattern = await prisma.pattern.findUniqueOrThrow({ where: { id: recommendation.patternId } });

  action = await prisma.recommendationAction.update({
    where: { id: action.id },
    data: { status: "approved", approvedByUserId, approvedAt: new Date() },
  });

  const sampleOccurrence = await prisma.patternOccurrence.findFirst({
    where: { patternId: pattern.id, outcome: "lost" },
  });

  let graph8ObjectType: string | null = null;
  let graph8ObjectId: string | null = null;
  let status = action.status;
  let error: string | null = null;

  try {
    if (action.actionType === "create_task") {
      const graph8Id = await provider.createTask({
        graph8DealId: sampleOccurrence?.dealId || "",
        title: recommendation.title,
        description:
          `${recommendation.explanation}\n\nRecommended action: ${recommendation.recommendedAction}\n\n` +
          `Department: ${recommendation.department}. Generated by Graph8 Revenue Learning ` +
          `from pattern '${pattern.name}' (${pattern.lostCount} lost / ${pattern.wonCount} won deals).`,
      });
      graph8ObjectType = "task";
      graph8ObjectId = graph8Id;
    } else {
      const graph8Id = await provider.createNote({
        graph8DealId: sampleOccurrence?.dealId || "",
        body: `Revenue Learning insight: ${recommendation.title}. ${recommendation.explanation}`,
      });
      graph8ObjectType = "note";
      graph8ObjectId = graph8Id;
    }
    status = "created";
    await prisma.recommendation.update({ where: { id: recommendation.id }, data: { status: "actioned" } });
  } catch (exc) {
    status = "failed";
    error = exc instanceof Error ? exc.message : String(exc);
  }

  action = await prisma.recommendationAction.update({
    where: { id: action.id },
    data: { status, error, graph8ObjectType, graph8ObjectId },
  });

  await prisma.auditLog.create({
    data: {
      organizationId,
      actorUserId: approvedByUserId,
      action: "approve_recommendation_action",
      entityType: "recommendation_action",
      entityId: action.id,
      logMetadata: {
        recommendation_id: recommendation.id,
        graph8_object_type: graph8ObjectType,
        graph8_object_id: graph8ObjectId,
        status,
      },
    },
  });

  return action;
}
