"""initial schema

Revision ID: e92be7074569
Revises: 
Create Date: 2026-09-26 21:33:16.022889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e92be7074569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_organization_id'), 'agent_runs', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('deal_analyses',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_identifier', sa.String(length=64), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('primary_factor_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='confidencelevel'), nullable=False),
    sa.Column('human_confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_CLARIFICATION', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_factor_id'], ['deal_factors.id'], name='fk_deal_analyses_primary_factor_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_analyses_deal_id'), 'deal_analyses', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_analyses_is_current'), 'deal_analyses', ['is_current'], unique=False)
    op.create_index(op.f('ix_deal_analyses_organization_id'), 'deal_analyses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deal_analyses_status'), 'deal_analyses', ['status'], unique=False)
    op.create_table('deals',
    sa.Column('graph8_deal_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.Enum('ENTERPRISE', 'MID_MARKET', 'SMB', name='dealsegment'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('stage_id', sa.String(length=255), nullable=True),
    sa.Column('stage_name', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.Enum('OPEN', 'WON', 'LOST', name='dealoutcome'), nullable=False),
    sa.Column('close_reason_raw', sa.String(length=1024), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_graph8_deal_id'), 'deals', ['graph8_deal_id'], unique=False)
    op.create_index(op.f('ix_deals_organization_id'), 'deals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deals_outcome'), 'deals', ['outcome'], unique=False)
    op.create_index(op.f('ix_deals_segment'), 'deals', ['segment'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PRODUCT_CAPABILITY_GAP', 'INTEGRATION_GAP', 'PRICING', 'PACKAGING', 'COMPETITOR', 'SECURITY', 'COMPLIANCE', 'PRIVACY', 'LEGAL', 'IMPLEMENTATION', 'SUPPORT', 'WRONG_FIT', 'MISSING_DECISION_MAKER', 'WEAK_CHAMPION', 'STAKEHOLDER_MISALIGNMENT', 'POOR_DISCOVERY', 'POOR_DEMO', 'SLOW_FOLLOWUP', 'PROPOSAL_DELAY', 'COMMUNICATION', 'VALUE_NOT_PROVEN', 'ROI_NOT_PROVEN', 'TIMING', 'BUDGET', 'PRIORITY_CHANGE', 'BUYER_PROJECT_CANCELLED', 'PROCUREMENT', 'INTERNAL_SELLER_DELAY', 'UNKNOWN', 'OTHER', name='factorcategory'), nullable=False),
    sa.Column('segment_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lost_count', sa.Integer(), nullable=False),
    sa.Column('won_count', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('pattern_strength', sa.Enum('ONE_OFF', 'EMERGING_PATTERN', 'RECURRING_PATTERN', 'STRONG_PATTERN', name='patternstrength'), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='confidencelevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', name='patternstatus'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_category'), 'patterns', ['category'], unique=False)
    op.create_index(op.f('ix_patterns_organization_id'), 'patterns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_patterns_status'), 'patterns', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('graph8_deal_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', name='webhookprocessingstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_event_id', name='uq_org_external_event')
    )
    op.create_index(op.f('ix_webhook_events_external_event_id'), 'webhook_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_graph8_deal_id'), 'webhook_events', ['graph8_deal_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_organization_id'), 'webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processing_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_table('deal_contacts',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CHAMPION', 'DECISION_MAKER', 'INFLUENCER', 'BLOCKER', 'COACH', 'END_USER', 'UNKNOWN', name='contactrole'), nullable=False),
    sa.Column('engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_contacts_deal_id'), 'deal_contacts', ['deal_id'], unique=False)
    op.create_table('deal_factors',
    sa.Column('deal_analysis_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('PRODUCT_CAPABILITY_GAP', 'INTEGRATION_GAP', 'PRICING', 'PACKAGING', 'COMPETITOR', 'SECURITY', 'COMPLIANCE', 'PRIVACY', 'LEGAL', 'IMPLEMENTATION', 'SUPPORT', 'WRONG_FIT', 'MISSING_DECISION_MAKER', 'WEAK_CHAMPION', 'STAKEHOLDER_MISALIGNMENT', 'POOR_DISCOVERY', 'POOR_DEMO', 'SLOW_FOLLOWUP', 'PROPOSAL_DELAY', 'COMMUNICATION', 'VALUE_NOT_PROVEN', 'ROI_NOT_PROVEN', 'TIMING', 'BUDGET', 'PRIORITY_CHANGE', 'BUYER_PROJECT_CANCELLED', 'PROCUREMENT', 'INTERNAL_SELLER_DELAY', 'UNKNOWN', 'OTHER', name='factorcategory'), nullable=False),
    sa.Column('specific_issue', sa.String(length=512), nullable=False),
    sa.Column('factor_type', sa.Enum('PRIMARY', 'SECONDARY', name='factortype'), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='confidencelevel'), nullable=False),
    sa.Column('preventability', sa.Enum('PREVENTABLE', 'POTENTIALLY_PREVENTABLE', 'NOT_PREVENTABLE', 'UNKNOWN', name='preventability'), nullable=False),
    sa.Column('department', sa.Enum('SALES', 'SALES_ENGINEERING', 'PRODUCT', 'ENGINEERING', 'PRICING', 'FINANCE', 'SECURITY', 'COMPLIANCE', 'PRIVACY', 'LEGAL', 'OPERATIONS', 'IMPLEMENTATION', 'LEADERSHIP', name='department'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deal_analysis_id'], ['deal_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_factors_category'), 'deal_factors', ['category'], unique=False)
    op.create_index(op.f('ix_deal_factors_deal_analysis_id'), 'deal_factors', ['deal_analysis_id'], unique=False)
    op.create_index(op.f('ix_deal_factors_organization_id'), 'deal_factors', ['organization_id'], unique=False)
    op.create_table('deal_snapshots',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_snapshots_deal_id'), 'deal_snapshots', ['deal_id'], unique=False)
    op.create_table('future_deal_warnings',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('similarity_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_deal_warnings_deal_id'), 'future_deal_warnings', ['deal_id'], unique=False)
    op.create_index(op.f('ix_future_deal_warnings_organization_id'), 'future_deal_warnings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_future_deal_warnings_pattern_id'), 'future_deal_warnings', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_future_deal_warnings_status'), 'future_deal_warnings', ['status'], unique=False)
    op.create_table('graph8_connections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('DEMO', 'LIVE', name='connectionmode'), nullable=False),
    sa.Column('status', sa.Enum('NOT_CONFIGURED', 'CONNECTED', 'ERROR', name='connectionstatus'), nullable=False),
    sa.Column('encrypted_api_key_ref', sa.String(length=512), nullable=True),
    sa.Column('graph8_org_id', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('human_feedback',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('selected_reason', sa.String(length=255), nullable=True),
    sa.Column('override_category', sa.Enum('PRODUCT_CAPABILITY_GAP', 'INTEGRATION_GAP', 'PRICING', 'PACKAGING', 'COMPETITOR', 'SECURITY', 'COMPLIANCE', 'PRIVACY', 'LEGAL', 'IMPLEMENTATION', 'SUPPORT', 'WRONG_FIT', 'MISSING_DECISION_MAKER', 'WEAK_CHAMPION', 'STAKEHOLDER_MISALIGNMENT', 'POOR_DISCOVERY', 'POOR_DEMO', 'SLOW_FOLLOWUP', 'PROPOSAL_DELAY', 'COMMUNICATION', 'VALUE_NOT_PROVEN', 'ROI_NOT_PROVEN', 'TIMING', 'BUDGET', 'PRIORITY_CHANGE', 'BUYER_PROJECT_CANCELLED', 'PROCUREMENT', 'INTERNAL_SELLER_DELAY', 'UNKNOWN', 'OTHER', name='factorcategory'), nullable=True),
    sa.Column('was_seller_controllable', sa.Boolean(), nullable=True),
    sa.Column('another_vendor_selected', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['deal_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_feedback_analysis_id'), 'human_feedback', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_human_feedback_deal_id'), 'human_feedback', ['deal_id'], unique=False)
    op.create_index(op.f('ix_human_feedback_organization_id'), 'human_feedback', ['organization_id'], unique=False)
    op.create_table('pattern_occurrences',
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('deal_factor_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_occurrences_deal_id'), 'pattern_occurrences', ['deal_id'], unique=False)
    op.create_index(op.f('ix_pattern_occurrences_pattern_id'), 'pattern_occurrences', ['pattern_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.Enum('SALES', 'SALES_ENGINEERING', 'PRODUCT', 'ENGINEERING', 'PRICING', 'FINANCE', 'SECURITY', 'COMPLIANCE', 'PRIVACY', 'LEGAL', 'OPERATIONS', 'IMPLEMENTATION', 'LEADERSHIP', name='department'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_department'), 'recommendations', ['department'], unique=False)
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recommendations_pattern_id'), 'recommendations', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REV_LEADER', 'MANAGER', 'REP', 'READ_ONLY', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('deal_evidence',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('factor_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('MEETING', 'TRANSCRIPT', 'DEAL_ACTIVITY', 'NOTE', 'CLOSE_REASON', 'STAKEHOLDER_DATA', 'SALESPERSON_CONFIRMATION', 'OTHER', name='evidencesourcetype'), nullable=False),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finding', sa.String(length=512), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('strength', sa.Enum('WEAK', 'MODERATE', 'STRONG', name='evidencestrength'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['deal_analyses.id'], ),
    sa.ForeignKeyConstraint(['factor_id'], ['deal_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_evidence_analysis_id'), 'deal_evidence', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_deal_evidence_deal_id'), 'deal_evidence', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_evidence_factor_id'), 'deal_evidence', ['factor_id'], unique=False)
    op.create_index(op.f('ix_deal_evidence_organization_id'), 'deal_evidence', ['organization_id'], unique=False)
    op.create_table('recommendation_actions',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graph8_object_type', sa.String(length=64), nullable=True),
    sa.Column('graph8_object_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_actions_recommendation_id'), 'recommendation_actions', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_actions_status'), 'recommendation_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_actions_status'), table_name='recommendation_actions')
    op.drop_index(op.f('ix_recommendation_actions_recommendation_id'), table_name='recommendation_actions')
    op.drop_table('recommendation_actions')
    op.drop_index(op.f('ix_deal_evidence_organization_id'), table_name='deal_evidence')
    op.drop_index(op.f('ix_deal_evidence_factor_id'), table_name='deal_evidence')
    op.drop_index(op.f('ix_deal_evidence_deal_id'), table_name='deal_evidence')
    op.drop_index(op.f('ix_deal_evidence_analysis_id'), table_name='deal_evidence')
    op.drop_table('deal_evidence')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_pattern_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_department'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_pattern_occurrences_pattern_id'), table_name='pattern_occurrences')
    op.drop_index(op.f('ix_pattern_occurrences_deal_id'), table_name='pattern_occurrences')
    op.drop_table('pattern_occurrences')
    op.drop_index(op.f('ix_human_feedback_organization_id'), table_name='human_feedback')
    op.drop_index(op.f('ix_human_feedback_deal_id'), table_name='human_feedback')
    op.drop_index(op.f('ix_human_feedback_analysis_id'), table_name='human_feedback')
    op.drop_table('human_feedback')
    op.drop_table('graph8_connections')
    op.drop_index(op.f('ix_future_deal_warnings_status'), table_name='future_deal_warnings')
    op.drop_index(op.f('ix_future_deal_warnings_pattern_id'), table_name='future_deal_warnings')
    op.drop_index(op.f('ix_future_deal_warnings_organization_id'), table_name='future_deal_warnings')
    op.drop_index(op.f('ix_future_deal_warnings_deal_id'), table_name='future_deal_warnings')
    op.drop_table('future_deal_warnings')
    op.drop_index(op.f('ix_deal_snapshots_deal_id'), table_name='deal_snapshots')
    op.drop_table('deal_snapshots')
    op.drop_index(op.f('ix_deal_factors_organization_id'), table_name='deal_factors')
    op.drop_index(op.f('ix_deal_factors_deal_analysis_id'), table_name='deal_factors')
    op.drop_index(op.f('ix_deal_factors_category'), table_name='deal_factors')
    op.drop_table('deal_factors')
    op.drop_index(op.f('ix_deal_contacts_deal_id'), table_name='deal_contacts')
    op.drop_table('deal_contacts')
    op.drop_index(op.f('ix_webhook_events_processing_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_organization_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_graph8_deal_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_external_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_patterns_status'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_organization_id'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_category'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_deals_segment'), table_name='deals')
    op.drop_index(op.f('ix_deals_outcome'), table_name='deals')
    op.drop_index(op.f('ix_deals_organization_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_graph8_deal_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_deal_analyses_status'), table_name='deal_analyses')
    op.drop_index(op.f('ix_deal_analyses_organization_id'), table_name='deal_analyses')
    op.drop_index(op.f('ix_deal_analyses_is_current'), table_name='deal_analyses')
    op.drop_index(op.f('ix_deal_analyses_deal_id'), table_name='deal_analyses')
    op.drop_table('deal_analyses')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_organization_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
